nameOverride: ""
fullnameOverride: ""

image:
  container: chefbook-backend-user-service
  registry: ""
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []

config:
  develop: false
  # Leave empty for stdout only
  logsPath: ""

  postgres:
    host: ""
    port: 5432
    dbName: chefbook-users

  s3:
    host: ""
    bucket: images

  rabbitmq:
    name: ""
    namespace: ""
    port: 5672
    vhost: ""

secrets:
  firebase:
    name: firebase-secrets
    credentialsRef: credentials
  postgres:
    name: postgres-secrets
    userRef: user
    passwordRef: password
  s3:
    name: s3-secrets
    accessKeyIdRef: accessKeyId
    secretAccessKeyRef: secretAccessKey
  rabbitmq:
    name: rabbitmq-secrets
    userRef: user
    passwordRef: password

service:
  type: ClusterIP
  port: 8080

replicaCount: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
