apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chefbook-backend-user-service.fullname" . }}-migrations-job
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chefbook-backend-user-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chefbook-backend-user-service.name" . }}-migration
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-migrations
          image: "{{ .Values.image.registry }}/{{ .Values.image.container }}-migrations:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.config.postgres.host }}
            - name: DB_PORT
              value: {{ .Values.config.postgres.port | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgres.name }}
                  key: {{ .Values.secrets.postgres.userRef }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgres.name }}
                  key: {{ .Values.secrets.postgres.passwordRef }}
            - name: DB_NAME
              value: {{ .Values.config.postgres.dbName }}
