// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/confirm-user-avatar-uploading.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmUserAvatarUploadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AvatarLink    string                 `protobuf:"bytes,2,opt,name=avatarLink,proto3" json:"avatarLink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUserAvatarUploadingRequest) Reset() {
	*x = ConfirmUserAvatarUploadingRequest{}
	mi := &file_v1_confirm_user_avatar_uploading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUserAvatarUploadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUserAvatarUploadingRequest) ProtoMessage() {}

func (x *ConfirmUserAvatarUploadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_confirm_user_avatar_uploading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUserAvatarUploadingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUserAvatarUploadingRequest) Descriptor() ([]byte, []int) {
	return file_v1_confirm_user_avatar_uploading_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmUserAvatarUploadingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmUserAvatarUploadingRequest) GetAvatarLink() string {
	if x != nil {
		return x.AvatarLink
	}
	return ""
}

type ConfirmUserAvatarUploadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUserAvatarUploadingResponse) Reset() {
	*x = ConfirmUserAvatarUploadingResponse{}
	mi := &file_v1_confirm_user_avatar_uploading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUserAvatarUploadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUserAvatarUploadingResponse) ProtoMessage() {}

func (x *ConfirmUserAvatarUploadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_confirm_user_avatar_uploading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUserAvatarUploadingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUserAvatarUploadingResponse) Descriptor() ([]byte, []int) {
	return file_v1_confirm_user_avatar_uploading_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmUserAvatarUploadingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_confirm_user_avatar_uploading_proto protoreflect.FileDescriptor

const file_v1_confirm_user_avatar_uploading_proto_rawDesc = "" +
	"\n" +
	"&v1/confirm-user-avatar-uploading.proto\x12\x02v1\"[\n" +
	"!ConfirmUserAvatarUploadingRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"avatarLink\x18\x02 \x01(\tR\n" +
	"avatarLink\">\n" +
	"\"ConfirmUserAvatarUploadingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-user/api/proto/v1b\x06proto3"

var (
	file_v1_confirm_user_avatar_uploading_proto_rawDescOnce sync.Once
	file_v1_confirm_user_avatar_uploading_proto_rawDescData []byte
)

func file_v1_confirm_user_avatar_uploading_proto_rawDescGZIP() []byte {
	file_v1_confirm_user_avatar_uploading_proto_rawDescOnce.Do(func() {
		file_v1_confirm_user_avatar_uploading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_confirm_user_avatar_uploading_proto_rawDesc), len(file_v1_confirm_user_avatar_uploading_proto_rawDesc)))
	})
	return file_v1_confirm_user_avatar_uploading_proto_rawDescData
}

var file_v1_confirm_user_avatar_uploading_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_confirm_user_avatar_uploading_proto_goTypes = []any{
	(*ConfirmUserAvatarUploadingRequest)(nil),  // 0: v1.ConfirmUserAvatarUploadingRequest
	(*ConfirmUserAvatarUploadingResponse)(nil), // 1: v1.ConfirmUserAvatarUploadingResponse
}
var file_v1_confirm_user_avatar_uploading_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_confirm_user_avatar_uploading_proto_init() }
func file_v1_confirm_user_avatar_uploading_proto_init() {
	if File_v1_confirm_user_avatar_uploading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_confirm_user_avatar_uploading_proto_rawDesc), len(file_v1_confirm_user_avatar_uploading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_confirm_user_avatar_uploading_proto_goTypes,
		DependencyIndexes: file_v1_confirm_user_avatar_uploading_proto_depIdxs,
		MessageInfos:      file_v1_confirm_user_avatar_uploading_proto_msgTypes,
	}.Build()
	File_v1_confirm_user_avatar_uploading_proto = out.File
	file_v1_confirm_user_avatar_uploading_proto_goTypes = nil
	file_v1_confirm_user_avatar_uploading_proto_depIdxs = nil
}
