// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/delete-user-avatar.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteUserAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserAvatarRequest) Reset() {
	*x = DeleteUserAvatarRequest{}
	mi := &file_v1_delete_user_avatar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserAvatarRequest) ProtoMessage() {}

func (x *DeleteUserAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_user_avatar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserAvatarRequest) Descriptor() ([]byte, []int) {
	return file_v1_delete_user_avatar_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteUserAvatarRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserAvatarResponse) Reset() {
	*x = DeleteUserAvatarResponse{}
	mi := &file_v1_delete_user_avatar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserAvatarResponse) ProtoMessage() {}

func (x *DeleteUserAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_user_avatar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserAvatarResponse) Descriptor() ([]byte, []int) {
	return file_v1_delete_user_avatar_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteUserAvatarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_delete_user_avatar_proto protoreflect.FileDescriptor

const file_v1_delete_user_avatar_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/delete-user-avatar.proto\x12\x02v1\"1\n" +
	"\x17DeleteUserAvatarRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x18DeleteUserAvatarResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-user/api/proto/v1b\x06proto3"

var (
	file_v1_delete_user_avatar_proto_rawDescOnce sync.Once
	file_v1_delete_user_avatar_proto_rawDescData []byte
)

func file_v1_delete_user_avatar_proto_rawDescGZIP() []byte {
	file_v1_delete_user_avatar_proto_rawDescOnce.Do(func() {
		file_v1_delete_user_avatar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_delete_user_avatar_proto_rawDesc), len(file_v1_delete_user_avatar_proto_rawDesc)))
	})
	return file_v1_delete_user_avatar_proto_rawDescData
}

var file_v1_delete_user_avatar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_delete_user_avatar_proto_goTypes = []any{
	(*DeleteUserAvatarRequest)(nil),  // 0: v1.DeleteUserAvatarRequest
	(*DeleteUserAvatarResponse)(nil), // 1: v1.DeleteUserAvatarResponse
}
var file_v1_delete_user_avatar_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_delete_user_avatar_proto_init() }
func file_v1_delete_user_avatar_proto_init() {
	if File_v1_delete_user_avatar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_delete_user_avatar_proto_rawDesc), len(file_v1_delete_user_avatar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_delete_user_avatar_proto_goTypes,
		DependencyIndexes: file_v1_delete_user_avatar_proto_depIdxs,
		MessageInfos:      file_v1_delete_user_avatar_proto_msgTypes,
	}.Build()
	File_v1_delete_user_avatar_proto = out.File
	file_v1_delete_user_avatar_proto_goTypes = nil
	file_v1_delete_user_avatar_proto_depIdxs = nil
}
