// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/generate-user-avatar-upload-link.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateUserAvatarUploadLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUserAvatarUploadLinkRequest) Reset() {
	*x = GenerateUserAvatarUploadLinkRequest{}
	mi := &file_v1_generate_user_avatar_upload_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUserAvatarUploadLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUserAvatarUploadLinkRequest) ProtoMessage() {}

func (x *GenerateUserAvatarUploadLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_user_avatar_upload_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUserAvatarUploadLinkRequest.ProtoReflect.Descriptor instead.
func (*GenerateUserAvatarUploadLinkRequest) Descriptor() ([]byte, []int) {
	return file_v1_generate_user_avatar_upload_link_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateUserAvatarUploadLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GenerateUserAvatarUploadLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarLink    string                 `protobuf:"bytes,1,opt,name=avatarLink,proto3" json:"avatarLink,omitempty"`
	UploadLink    string                 `protobuf:"bytes,2,opt,name=uploadLink,proto3" json:"uploadLink,omitempty"`
	FormData      map[string]string      `protobuf:"bytes,3,rep,name=formData,proto3" json:"formData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxSize       int64                  `protobuf:"varint,4,opt,name=maxSize,proto3" json:"maxSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUserAvatarUploadLinkResponse) Reset() {
	*x = GenerateUserAvatarUploadLinkResponse{}
	mi := &file_v1_generate_user_avatar_upload_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUserAvatarUploadLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUserAvatarUploadLinkResponse) ProtoMessage() {}

func (x *GenerateUserAvatarUploadLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_user_avatar_upload_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUserAvatarUploadLinkResponse.ProtoReflect.Descriptor instead.
func (*GenerateUserAvatarUploadLinkResponse) Descriptor() ([]byte, []int) {
	return file_v1_generate_user_avatar_upload_link_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateUserAvatarUploadLinkResponse) GetAvatarLink() string {
	if x != nil {
		return x.AvatarLink
	}
	return ""
}

func (x *GenerateUserAvatarUploadLinkResponse) GetUploadLink() string {
	if x != nil {
		return x.UploadLink
	}
	return ""
}

func (x *GenerateUserAvatarUploadLinkResponse) GetFormData() map[string]string {
	if x != nil {
		return x.FormData
	}
	return nil
}

func (x *GenerateUserAvatarUploadLinkResponse) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

var File_v1_generate_user_avatar_upload_link_proto protoreflect.FileDescriptor

const file_v1_generate_user_avatar_upload_link_proto_rawDesc = "" +
	"\n" +
	")v1/generate-user-avatar-upload-link.proto\x12\x02v1\"=\n" +
	"#GenerateUserAvatarUploadLinkRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x91\x02\n" +
	"$GenerateUserAvatarUploadLinkResponse\x12\x1e\n" +
	"\n" +
	"avatarLink\x18\x01 \x01(\tR\n" +
	"avatarLink\x12\x1e\n" +
	"\n" +
	"uploadLink\x18\x02 \x01(\tR\n" +
	"uploadLink\x12R\n" +
	"\bformData\x18\x03 \x03(\v26.v1.GenerateUserAvatarUploadLinkResponse.FormDataEntryR\bformData\x12\x18\n" +
	"\amaxSize\x18\x04 \x01(\x03R\amaxSize\x1a;\n" +
	"\rFormDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B;Z9github.com/mephistolie/chefbook-backend-user/api/proto/v1b\x06proto3"

var (
	file_v1_generate_user_avatar_upload_link_proto_rawDescOnce sync.Once
	file_v1_generate_user_avatar_upload_link_proto_rawDescData []byte
)

func file_v1_generate_user_avatar_upload_link_proto_rawDescGZIP() []byte {
	file_v1_generate_user_avatar_upload_link_proto_rawDescOnce.Do(func() {
		file_v1_generate_user_avatar_upload_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_generate_user_avatar_upload_link_proto_rawDesc), len(file_v1_generate_user_avatar_upload_link_proto_rawDesc)))
	})
	return file_v1_generate_user_avatar_upload_link_proto_rawDescData
}

var file_v1_generate_user_avatar_upload_link_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_generate_user_avatar_upload_link_proto_goTypes = []any{
	(*GenerateUserAvatarUploadLinkRequest)(nil),  // 0: v1.GenerateUserAvatarUploadLinkRequest
	(*GenerateUserAvatarUploadLinkResponse)(nil), // 1: v1.GenerateUserAvatarUploadLinkResponse
	nil, // 2: v1.GenerateUserAvatarUploadLinkResponse.FormDataEntry
}
var file_v1_generate_user_avatar_upload_link_proto_depIdxs = []int32{
	2, // 0: v1.GenerateUserAvatarUploadLinkResponse.formData:type_name -> v1.GenerateUserAvatarUploadLinkResponse.FormDataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_generate_user_avatar_upload_link_proto_init() }
func file_v1_generate_user_avatar_upload_link_proto_init() {
	if File_v1_generate_user_avatar_upload_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_generate_user_avatar_upload_link_proto_rawDesc), len(file_v1_generate_user_avatar_upload_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_generate_user_avatar_upload_link_proto_goTypes,
		DependencyIndexes: file_v1_generate_user_avatar_upload_link_proto_depIdxs,
		MessageInfos:      file_v1_generate_user_avatar_upload_link_proto_msgTypes,
	}.Build()
	File_v1_generate_user_avatar_upload_link_proto = out.File
	file_v1_generate_user_avatar_upload_link_proto_goTypes = nil
	file_v1_generate_user_avatar_upload_link_proto_depIdxs = nil
}
