// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/get-users-min-info.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   *string                `protobuf:"bytes,1,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	Avatar        *string                `protobuf:"bytes,2,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMinInfo) Reset() {
	*x = UserMinInfo{}
	mi := &file_v1_get_users_min_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMinInfo) ProtoMessage() {}

func (x *UserMinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_users_min_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMinInfo.ProtoReflect.Descriptor instead.
func (*UserMinInfo) Descriptor() ([]byte, []int) {
	return file_v1_get_users_min_info_proto_rawDescGZIP(), []int{0}
}

func (x *UserMinInfo) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UserMinInfo) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type GetUsersMinInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersMinInfoRequest) Reset() {
	*x = GetUsersMinInfoRequest{}
	mi := &file_v1_get_users_min_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersMinInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersMinInfoRequest) ProtoMessage() {}

func (x *GetUsersMinInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_users_min_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersMinInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUsersMinInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_users_min_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersMinInfoRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersMinInfoResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Infos         map[string]*UserMinInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersMinInfoResponse) Reset() {
	*x = GetUsersMinInfoResponse{}
	mi := &file_v1_get_users_min_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersMinInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersMinInfoResponse) ProtoMessage() {}

func (x *GetUsersMinInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_users_min_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersMinInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUsersMinInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_users_min_info_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersMinInfoResponse) GetInfos() map[string]*UserMinInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_v1_get_users_min_info_proto protoreflect.FileDescriptor

const file_v1_get_users_min_info_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/get-users-min-info.proto\x12\x02v1\"l\n" +
	"\vUserMinInfo\x12%\n" +
	"\vdisplayName\x18\x01 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x02 \x01(\tH\x01R\x06avatar\x88\x01\x01B\x0e\n" +
	"\f_displayNameB\t\n" +
	"\a_avatar\"2\n" +
	"\x16GetUsersMinInfoRequest\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\tR\auserIds\"\xa2\x01\n" +
	"\x17GetUsersMinInfoResponse\x12<\n" +
	"\x05infos\x18\x01 \x03(\v2&.v1.GetUsersMinInfoResponse.InfosEntryR\x05infos\x1aI\n" +
	"\n" +
	"InfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.v1.UserMinInfoR\x05value:\x028\x01B;Z9github.com/mephistolie/chefbook-backend-user/api/proto/v1b\x06proto3"

var (
	file_v1_get_users_min_info_proto_rawDescOnce sync.Once
	file_v1_get_users_min_info_proto_rawDescData []byte
)

func file_v1_get_users_min_info_proto_rawDescGZIP() []byte {
	file_v1_get_users_min_info_proto_rawDescOnce.Do(func() {
		file_v1_get_users_min_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_get_users_min_info_proto_rawDesc), len(file_v1_get_users_min_info_proto_rawDesc)))
	})
	return file_v1_get_users_min_info_proto_rawDescData
}

var file_v1_get_users_min_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_get_users_min_info_proto_goTypes = []any{
	(*UserMinInfo)(nil),             // 0: v1.UserMinInfo
	(*GetUsersMinInfoRequest)(nil),  // 1: v1.GetUsersMinInfoRequest
	(*GetUsersMinInfoResponse)(nil), // 2: v1.GetUsersMinInfoResponse
	nil,                             // 3: v1.GetUsersMinInfoResponse.InfosEntry
}
var file_v1_get_users_min_info_proto_depIdxs = []int32{
	3, // 0: v1.GetUsersMinInfoResponse.infos:type_name -> v1.GetUsersMinInfoResponse.InfosEntry
	0, // 1: v1.GetUsersMinInfoResponse.InfosEntry.value:type_name -> v1.UserMinInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_get_users_min_info_proto_init() }
func file_v1_get_users_min_info_proto_init() {
	if File_v1_get_users_min_info_proto != nil {
		return
	}
	file_v1_get_users_min_info_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_get_users_min_info_proto_rawDesc), len(file_v1_get_users_min_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_users_min_info_proto_goTypes,
		DependencyIndexes: file_v1_get_users_min_info_proto_depIdxs,
		MessageInfos:      file_v1_get_users_min_info_proto_msgTypes,
	}.Build()
	File_v1_get_users_min_info_proto = out.File
	file_v1_get_users_min_info_proto_goTypes = nil
	file_v1_get_users_min_info_proto_depIdxs = nil
}
