// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/get-user-info.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_v1_get_user_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_user_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_user_info_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Avatar        *string                `protobuf:"bytes,4,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_v1_get_user_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_user_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_user_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoResponse) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *GetUserInfoResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *GetUserInfoResponse) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

var File_v1_get_user_info_proto protoreflect.FileDescriptor

const file_v1_get_user_info_proto_rawDesc = "" +
	"\n" +
	"\x16v1/get-user-info.proto\x12\x02v1\",\n" +
	"\x12GetUserInfoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\xc3\x01\n" +
	"\x13GetUserInfoResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\vdisplayName\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x04 \x01(\tH\x02R\x06avatar\x88\x01\x01B\x0e\n" +
	"\f_displayNameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_avatarB;Z9github.com/mephistolie/chefbook-backend-user/api/proto/v1b\x06proto3"

var (
	file_v1_get_user_info_proto_rawDescOnce sync.Once
	file_v1_get_user_info_proto_rawDescData []byte
)

func file_v1_get_user_info_proto_rawDescGZIP() []byte {
	file_v1_get_user_info_proto_rawDescOnce.Do(func() {
		file_v1_get_user_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_get_user_info_proto_rawDesc), len(file_v1_get_user_info_proto_rawDesc)))
	})
	return file_v1_get_user_info_proto_rawDescData
}

var file_v1_get_user_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_get_user_info_proto_goTypes = []any{
	(*GetUserInfoRequest)(nil),  // 0: v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil), // 1: v1.GetUserInfoResponse
}
var file_v1_get_user_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_get_user_info_proto_init() }
func file_v1_get_user_info_proto_init() {
	if File_v1_get_user_info_proto != nil {
		return
	}
	file_v1_get_user_info_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_get_user_info_proto_rawDesc), len(file_v1_get_user_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_user_info_proto_goTypes,
		DependencyIndexes: file_v1_get_user_info_proto_depIdxs,
		MessageInfos:      file_v1_get_user_info_proto_msgTypes,
	}.Build()
	File_v1_get_user_info_proto = out.File
	file_v1_get_user_info_proto_goTypes = nil
	file_v1_get_user_info_proto_depIdxs = nil
}
