// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/set-user-display-name.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUserDisplayNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDisplayNameRequest) Reset() {
	*x = SetUserDisplayNameRequest{}
	mi := &file_v1_set_user_display_name_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDisplayNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDisplayNameRequest) ProtoMessage() {}

func (x *SetUserDisplayNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_set_user_display_name_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDisplayNameRequest.ProtoReflect.Descriptor instead.
func (*SetUserDisplayNameRequest) Descriptor() ([]byte, []int) {
	return file_v1_set_user_display_name_proto_rawDescGZIP(), []int{0}
}

func (x *SetUserDisplayNameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserDisplayNameRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

type SetUserDisplayNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDisplayNameResponse) Reset() {
	*x = SetUserDisplayNameResponse{}
	mi := &file_v1_set_user_display_name_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDisplayNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDisplayNameResponse) ProtoMessage() {}

func (x *SetUserDisplayNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_set_user_display_name_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDisplayNameResponse.ProtoReflect.Descriptor instead.
func (*SetUserDisplayNameResponse) Descriptor() ([]byte, []int) {
	return file_v1_set_user_display_name_proto_rawDescGZIP(), []int{1}
}

func (x *SetUserDisplayNameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_set_user_display_name_proto protoreflect.FileDescriptor

const file_v1_set_user_display_name_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/set-user-display-name.proto\x12\x02v1\"j\n" +
	"\x19SetUserDisplayNameRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\vdisplayName\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01B\x0e\n" +
	"\f_displayName\"6\n" +
	"\x1aSetUserDisplayNameResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-user/api/proto/v1b\x06proto3"

var (
	file_v1_set_user_display_name_proto_rawDescOnce sync.Once
	file_v1_set_user_display_name_proto_rawDescData []byte
)

func file_v1_set_user_display_name_proto_rawDescGZIP() []byte {
	file_v1_set_user_display_name_proto_rawDescOnce.Do(func() {
		file_v1_set_user_display_name_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_set_user_display_name_proto_rawDesc), len(file_v1_set_user_display_name_proto_rawDesc)))
	})
	return file_v1_set_user_display_name_proto_rawDescData
}

var file_v1_set_user_display_name_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_set_user_display_name_proto_goTypes = []any{
	(*SetUserDisplayNameRequest)(nil),  // 0: v1.SetUserDisplayNameRequest
	(*SetUserDisplayNameResponse)(nil), // 1: v1.SetUserDisplayNameResponse
}
var file_v1_set_user_display_name_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_set_user_display_name_proto_init() }
func file_v1_set_user_display_name_proto_init() {
	if File_v1_set_user_display_name_proto != nil {
		return
	}
	file_v1_set_user_display_name_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_set_user_display_name_proto_rawDesc), len(file_v1_set_user_display_name_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_set_user_display_name_proto_goTypes,
		DependencyIndexes: file_v1_set_user_display_name_proto_depIdxs,
		MessageInfos:      file_v1_set_user_display_name_proto_msgTypes,
	}.Build()
	File_v1_set_user_display_name_proto = out.File
	file_v1_set_user_display_name_proto_goTypes = nil
	file_v1_set_user_display_name_proto_depIdxs = nil
}
