// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: v1/user-service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_GetUserInfo_FullMethodName                  = "/v1.UserService/GetUserInfo"
	UserService_SetUserName_FullMethodName                  = "/v1.UserService/SetUserName"
	UserService_SetUserDescription_FullMethodName           = "/v1.UserService/SetUserDescription"
	UserService_GenerateUserAvatarUploadLink_FullMethodName = "/v1.UserService/GenerateUserAvatarUploadLink"
	UserService_ConfirmUserAvatarUploading_FullMethodName   = "/v1.UserService/ConfirmUserAvatarUploading"
	UserService_DeleteUserAvatar_FullMethodName             = "/v1.UserService/DeleteUserAvatar"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	SetUserName(ctx context.Context, in *SetUserNameRequest, opts ...grpc.CallOption) (*SetUserNameResponse, error)
	SetUserDescription(ctx context.Context, in *SetUserDescriptionRequest, opts ...grpc.CallOption) (*SetUserDescriptionResponse, error)
	GenerateUserAvatarUploadLink(ctx context.Context, in *GenerateUserAvatarUploadLinkRequest, opts ...grpc.CallOption) (*GenerateUserAvatarUploadLinkResponse, error)
	ConfirmUserAvatarUploading(ctx context.Context, in *ConfirmUserAvatarUploadingRequest, opts ...grpc.CallOption) (*ConfirmUserAvatarUploadingResponse, error)
	DeleteUserAvatar(ctx context.Context, in *DeleteUserAvatarRequest, opts ...grpc.CallOption) (*DeleteUserAvatarResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetUserName(ctx context.Context, in *SetUserNameRequest, opts ...grpc.CallOption) (*SetUserNameResponse, error) {
	out := new(SetUserNameResponse)
	err := c.cc.Invoke(ctx, UserService_SetUserName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetUserDescription(ctx context.Context, in *SetUserDescriptionRequest, opts ...grpc.CallOption) (*SetUserDescriptionResponse, error) {
	out := new(SetUserDescriptionResponse)
	err := c.cc.Invoke(ctx, UserService_SetUserDescription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GenerateUserAvatarUploadLink(ctx context.Context, in *GenerateUserAvatarUploadLinkRequest, opts ...grpc.CallOption) (*GenerateUserAvatarUploadLinkResponse, error) {
	out := new(GenerateUserAvatarUploadLinkResponse)
	err := c.cc.Invoke(ctx, UserService_GenerateUserAvatarUploadLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ConfirmUserAvatarUploading(ctx context.Context, in *ConfirmUserAvatarUploadingRequest, opts ...grpc.CallOption) (*ConfirmUserAvatarUploadingResponse, error) {
	out := new(ConfirmUserAvatarUploadingResponse)
	err := c.cc.Invoke(ctx, UserService_ConfirmUserAvatarUploading_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserAvatar(ctx context.Context, in *DeleteUserAvatarRequest, opts ...grpc.CallOption) (*DeleteUserAvatarResponse, error) {
	out := new(DeleteUserAvatarResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteUserAvatar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	SetUserName(context.Context, *SetUserNameRequest) (*SetUserNameResponse, error)
	SetUserDescription(context.Context, *SetUserDescriptionRequest) (*SetUserDescriptionResponse, error)
	GenerateUserAvatarUploadLink(context.Context, *GenerateUserAvatarUploadLinkRequest) (*GenerateUserAvatarUploadLinkResponse, error)
	ConfirmUserAvatarUploading(context.Context, *ConfirmUserAvatarUploadingRequest) (*ConfirmUserAvatarUploadingResponse, error)
	DeleteUserAvatar(context.Context, *DeleteUserAvatarRequest) (*DeleteUserAvatarResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServiceServer) SetUserName(context.Context, *SetUserNameRequest) (*SetUserNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserName not implemented")
}
func (UnimplementedUserServiceServer) SetUserDescription(context.Context, *SetUserDescriptionRequest) (*SetUserDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserDescription not implemented")
}
func (UnimplementedUserServiceServer) GenerateUserAvatarUploadLink(context.Context, *GenerateUserAvatarUploadLinkRequest) (*GenerateUserAvatarUploadLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateUserAvatarUploadLink not implemented")
}
func (UnimplementedUserServiceServer) ConfirmUserAvatarUploading(context.Context, *ConfirmUserAvatarUploadingRequest) (*ConfirmUserAvatarUploadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmUserAvatarUploading not implemented")
}
func (UnimplementedUserServiceServer) DeleteUserAvatar(context.Context, *DeleteUserAvatarRequest) (*DeleteUserAvatarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserAvatar not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetUserName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetUserName(ctx, req.(*SetUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetUserDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetUserDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetUserDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetUserDescription(ctx, req.(*SetUserDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GenerateUserAvatarUploadLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUserAvatarUploadLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GenerateUserAvatarUploadLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GenerateUserAvatarUploadLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GenerateUserAvatarUploadLink(ctx, req.(*GenerateUserAvatarUploadLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ConfirmUserAvatarUploading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUserAvatarUploadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ConfirmUserAvatarUploading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ConfirmUserAvatarUploading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ConfirmUserAvatarUploading(ctx, req.(*ConfirmUserAvatarUploadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUserAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserAvatar(ctx, req.(*DeleteUserAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
		{
			MethodName: "SetUserName",
			Handler:    _UserService_SetUserName_Handler,
		},
		{
			MethodName: "SetUserDescription",
			Handler:    _UserService_SetUserDescription_Handler,
		},
		{
			MethodName: "GenerateUserAvatarUploadLink",
			Handler:    _UserService_GenerateUserAvatarUploadLink_Handler,
		},
		{
			MethodName: "ConfirmUserAvatarUploading",
			Handler:    _UserService_ConfirmUserAvatarUploading_Handler,
		},
		{
			MethodName: "DeleteUserAvatar",
			Handler:    _UserService_DeleteUserAvatar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/user-service.proto",
}
