// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: v1/user-service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetUsersMinInfo_FullMethodName              = "/v1.UserService/GetUsersMinInfo"
	UserService_GetUserInfo_FullMethodName                  = "/v1.UserService/GetUserInfo"
	UserService_SetUserDisplayName_FullMethodName           = "/v1.UserService/SetUserDisplayName"
	UserService_SetUserDescription_FullMethodName           = "/v1.UserService/SetUserDescription"
	UserService_GenerateUserAvatarUploadLink_FullMethodName = "/v1.UserService/GenerateUserAvatarUploadLink"
	UserService_ConfirmUserAvatarUploading_FullMethodName   = "/v1.UserService/ConfirmUserAvatarUploading"
	UserService_DeleteUserAvatar_FullMethodName             = "/v1.UserService/DeleteUserAvatar"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUsersMinInfo(ctx context.Context, in *GetUsersMinInfoRequest, opts ...grpc.CallOption) (*GetUsersMinInfoResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	SetUserDisplayName(ctx context.Context, in *SetUserDisplayNameRequest, opts ...grpc.CallOption) (*SetUserDisplayNameResponse, error)
	SetUserDescription(ctx context.Context, in *SetUserDescriptionRequest, opts ...grpc.CallOption) (*SetUserDescriptionResponse, error)
	GenerateUserAvatarUploadLink(ctx context.Context, in *GenerateUserAvatarUploadLinkRequest, opts ...grpc.CallOption) (*GenerateUserAvatarUploadLinkResponse, error)
	ConfirmUserAvatarUploading(ctx context.Context, in *ConfirmUserAvatarUploadingRequest, opts ...grpc.CallOption) (*ConfirmUserAvatarUploadingResponse, error)
	DeleteUserAvatar(ctx context.Context, in *DeleteUserAvatarRequest, opts ...grpc.CallOption) (*DeleteUserAvatarResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUsersMinInfo(ctx context.Context, in *GetUsersMinInfoRequest, opts ...grpc.CallOption) (*GetUsersMinInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersMinInfoResponse)
	err := c.cc.Invoke(ctx, UserService_GetUsersMinInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetUserDisplayName(ctx context.Context, in *SetUserDisplayNameRequest, opts ...grpc.CallOption) (*SetUserDisplayNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserDisplayNameResponse)
	err := c.cc.Invoke(ctx, UserService_SetUserDisplayName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetUserDescription(ctx context.Context, in *SetUserDescriptionRequest, opts ...grpc.CallOption) (*SetUserDescriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserDescriptionResponse)
	err := c.cc.Invoke(ctx, UserService_SetUserDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GenerateUserAvatarUploadLink(ctx context.Context, in *GenerateUserAvatarUploadLinkRequest, opts ...grpc.CallOption) (*GenerateUserAvatarUploadLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateUserAvatarUploadLinkResponse)
	err := c.cc.Invoke(ctx, UserService_GenerateUserAvatarUploadLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ConfirmUserAvatarUploading(ctx context.Context, in *ConfirmUserAvatarUploadingRequest, opts ...grpc.CallOption) (*ConfirmUserAvatarUploadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmUserAvatarUploadingResponse)
	err := c.cc.Invoke(ctx, UserService_ConfirmUserAvatarUploading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserAvatar(ctx context.Context, in *DeleteUserAvatarRequest, opts ...grpc.CallOption) (*DeleteUserAvatarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserAvatarResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteUserAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	GetUsersMinInfo(context.Context, *GetUsersMinInfoRequest) (*GetUsersMinInfoResponse, error)
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	SetUserDisplayName(context.Context, *SetUserDisplayNameRequest) (*SetUserDisplayNameResponse, error)
	SetUserDescription(context.Context, *SetUserDescriptionRequest) (*SetUserDescriptionResponse, error)
	GenerateUserAvatarUploadLink(context.Context, *GenerateUserAvatarUploadLinkRequest) (*GenerateUserAvatarUploadLinkResponse, error)
	ConfirmUserAvatarUploading(context.Context, *ConfirmUserAvatarUploadingRequest) (*ConfirmUserAvatarUploadingResponse, error)
	DeleteUserAvatar(context.Context, *DeleteUserAvatarRequest) (*DeleteUserAvatarResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUsersMinInfo(context.Context, *GetUsersMinInfoRequest) (*GetUsersMinInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersMinInfo not implemented")
}
func (UnimplementedUserServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServiceServer) SetUserDisplayName(context.Context, *SetUserDisplayNameRequest) (*SetUserDisplayNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserDisplayName not implemented")
}
func (UnimplementedUserServiceServer) SetUserDescription(context.Context, *SetUserDescriptionRequest) (*SetUserDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserDescription not implemented")
}
func (UnimplementedUserServiceServer) GenerateUserAvatarUploadLink(context.Context, *GenerateUserAvatarUploadLinkRequest) (*GenerateUserAvatarUploadLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateUserAvatarUploadLink not implemented")
}
func (UnimplementedUserServiceServer) ConfirmUserAvatarUploading(context.Context, *ConfirmUserAvatarUploadingRequest) (*ConfirmUserAvatarUploadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmUserAvatarUploading not implemented")
}
func (UnimplementedUserServiceServer) DeleteUserAvatar(context.Context, *DeleteUserAvatarRequest) (*DeleteUserAvatarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserAvatar not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUsersMinInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersMinInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsersMinInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUsersMinInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsersMinInfo(ctx, req.(*GetUsersMinInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetUserDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserDisplayNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetUserDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetUserDisplayName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetUserDisplayName(ctx, req.(*SetUserDisplayNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetUserDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetUserDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetUserDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetUserDescription(ctx, req.(*SetUserDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GenerateUserAvatarUploadLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUserAvatarUploadLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GenerateUserAvatarUploadLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GenerateUserAvatarUploadLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GenerateUserAvatarUploadLink(ctx, req.(*GenerateUserAvatarUploadLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ConfirmUserAvatarUploading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUserAvatarUploadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ConfirmUserAvatarUploading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ConfirmUserAvatarUploading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ConfirmUserAvatarUploading(ctx, req.(*ConfirmUserAvatarUploadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUserAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserAvatar(ctx, req.(*DeleteUserAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsersMinInfo",
			Handler:    _UserService_GetUsersMinInfo_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
		{
			MethodName: "SetUserDisplayName",
			Handler:    _UserService_SetUserDisplayName_Handler,
		},
		{
			MethodName: "SetUserDescription",
			Handler:    _UserService_SetUserDescription_Handler,
		},
		{
			MethodName: "GenerateUserAvatarUploadLink",
			Handler:    _UserService_GenerateUserAvatarUploadLink_Handler,
		},
		{
			MethodName: "ConfirmUserAvatarUploading",
			Handler:    _UserService_ConfirmUserAvatarUploading_Handler,
		},
		{
			MethodName: "DeleteUserAvatar",
			Handler:    _UserService_DeleteUserAvatar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/user-service.proto",
}
