// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/user-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_user_service_proto protoreflect.FileDescriptor

const file_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x15v1/user-service.proto\x12\x02v1\x1a\x1bv1/get-users-min-info.proto\x1a\x16v1/get-user-info.proto\x1a\x1ev1/set-user-display-name.proto\x1a\x1dv1/set-user-description.proto\x1a)v1/generate-user-avatar-upload-link.proto\x1a&v1/confirm-user-avatar-uploading.proto\x1a\x1bv1/delete-user-avatar.proto2\xf2\x04\n" +
	"\vUserService\x12J\n" +
	"\x0fGetUsersMinInfo\x12\x1a.v1.GetUsersMinInfoRequest\x1a\x1b.v1.GetUsersMinInfoResponse\x12>\n" +
	"\vGetUserInfo\x12\x16.v1.GetUserInfoRequest\x1a\x17.v1.GetUserInfoResponse\x12S\n" +
	"\x12SetUserDisplayName\x12\x1d.v1.SetUserDisplayNameRequest\x1a\x1e.v1.SetUserDisplayNameResponse\x12S\n" +
	"\x12SetUserDescription\x12\x1d.v1.SetUserDescriptionRequest\x1a\x1e.v1.SetUserDescriptionResponse\x12q\n" +
	"\x1cGenerateUserAvatarUploadLink\x12'.v1.GenerateUserAvatarUploadLinkRequest\x1a(.v1.GenerateUserAvatarUploadLinkResponse\x12k\n" +
	"\x1aConfirmUserAvatarUploading\x12%.v1.ConfirmUserAvatarUploadingRequest\x1a&.v1.ConfirmUserAvatarUploadingResponse\x12M\n" +
	"\x10DeleteUserAvatar\x12\x1b.v1.DeleteUserAvatarRequest\x1a\x1c.v1.DeleteUserAvatarResponseB;Z9github.com/mephistolie/chefbook-backend-user/api/proto/v1b\x06proto3"

var file_v1_user_service_proto_goTypes = []any{
	(*GetUsersMinInfoRequest)(nil),               // 0: v1.GetUsersMinInfoRequest
	(*GetUserInfoRequest)(nil),                   // 1: v1.GetUserInfoRequest
	(*SetUserDisplayNameRequest)(nil),            // 2: v1.SetUserDisplayNameRequest
	(*SetUserDescriptionRequest)(nil),            // 3: v1.SetUserDescriptionRequest
	(*GenerateUserAvatarUploadLinkRequest)(nil),  // 4: v1.GenerateUserAvatarUploadLinkRequest
	(*ConfirmUserAvatarUploadingRequest)(nil),    // 5: v1.ConfirmUserAvatarUploadingRequest
	(*DeleteUserAvatarRequest)(nil),              // 6: v1.DeleteUserAvatarRequest
	(*GetUsersMinInfoResponse)(nil),              // 7: v1.GetUsersMinInfoResponse
	(*GetUserInfoResponse)(nil),                  // 8: v1.GetUserInfoResponse
	(*SetUserDisplayNameResponse)(nil),           // 9: v1.SetUserDisplayNameResponse
	(*SetUserDescriptionResponse)(nil),           // 10: v1.SetUserDescriptionResponse
	(*GenerateUserAvatarUploadLinkResponse)(nil), // 11: v1.GenerateUserAvatarUploadLinkResponse
	(*ConfirmUserAvatarUploadingResponse)(nil),   // 12: v1.ConfirmUserAvatarUploadingResponse
	(*DeleteUserAvatarResponse)(nil),             // 13: v1.DeleteUserAvatarResponse
}
var file_v1_user_service_proto_depIdxs = []int32{
	0,  // 0: v1.UserService.GetUsersMinInfo:input_type -> v1.GetUsersMinInfoRequest
	1,  // 1: v1.UserService.GetUserInfo:input_type -> v1.GetUserInfoRequest
	2,  // 2: v1.UserService.SetUserDisplayName:input_type -> v1.SetUserDisplayNameRequest
	3,  // 3: v1.UserService.SetUserDescription:input_type -> v1.SetUserDescriptionRequest
	4,  // 4: v1.UserService.GenerateUserAvatarUploadLink:input_type -> v1.GenerateUserAvatarUploadLinkRequest
	5,  // 5: v1.UserService.ConfirmUserAvatarUploading:input_type -> v1.ConfirmUserAvatarUploadingRequest
	6,  // 6: v1.UserService.DeleteUserAvatar:input_type -> v1.DeleteUserAvatarRequest
	7,  // 7: v1.UserService.GetUsersMinInfo:output_type -> v1.GetUsersMinInfoResponse
	8,  // 8: v1.UserService.GetUserInfo:output_type -> v1.GetUserInfoResponse
	9,  // 9: v1.UserService.SetUserDisplayName:output_type -> v1.SetUserDisplayNameResponse
	10, // 10: v1.UserService.SetUserDescription:output_type -> v1.SetUserDescriptionResponse
	11, // 11: v1.UserService.GenerateUserAvatarUploadLink:output_type -> v1.GenerateUserAvatarUploadLinkResponse
	12, // 12: v1.UserService.ConfirmUserAvatarUploading:output_type -> v1.ConfirmUserAvatarUploadingResponse
	13, // 13: v1.UserService.DeleteUserAvatar:output_type -> v1.DeleteUserAvatarResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_user_service_proto_init() }
func file_v1_user_service_proto_init() {
	if File_v1_user_service_proto != nil {
		return
	}
	file_v1_get_users_min_info_proto_init()
	file_v1_get_user_info_proto_init()
	file_v1_set_user_display_name_proto_init()
	file_v1_set_user_description_proto_init()
	file_v1_generate_user_avatar_upload_link_proto_init()
	file_v1_confirm_user_avatar_uploading_proto_init()
	file_v1_delete_user_avatar_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_service_proto_rawDesc), len(file_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_service_proto_goTypes,
		DependencyIndexes: file_v1_user_service_proto_depIdxs,
	}.Build()
	File_v1_user_service_proto = out.File
	file_v1_user_service_proto_goTypes = nil
	file_v1_user_service_proto_depIdxs = nil
}
